parameters:
#    proyectos_departamento.example.class: Proyectos\DepartamentoBundle\Example

services:
#    proyectos_departamento.example:
#        class: %proyectos_departamento.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
